// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvrgjyyflojdiklqepqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2cmdqeXlmbG9qZGlrbHFlcHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDI4NjksImV4cCI6MjA3MzE3ODg2OX0.SeSjoz670SEzcmRjQd1HWv8kHxHKaLzDMKxDctTr0Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});